# Generated by Django 6.1.1 on 2026-09-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.IntegerField(help_text='OPIS Truckstop ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=3, help_text='Retail price per gallon', max_digits=6)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geocode_source', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['station_id'],
                'indexes': [models.Index(fields=['lat', 'lon'], name='stations_st_lat_91f89c_idx')],
            },
        ),
    ]
